### ISSUE TITLE
Where is the HTMXCSSHash used?

### ISSUE THREAD

**Issue by GoodiesHQ** [TomDoesTech/GOTTH#28]
This value is not derived from the tailwind CSS files, or seemingly any of the static files that I can find.

HtmxCSSHash:     "sha256-pgn1TCGZX6O77zDvy0oTODMOxemn0oj0LeCnQTRj7Kg=",

What file was used to calculate this?

**Comment by ApourtArtt** [comment]
It was found from the CSS injected by HTMX.
You can find it in your <head>, the last <style> tag is HTMX css.
Copy the entire line (everything excluding <style> and </style>, include every whitespace)
Then you can run something such as:
```py
content = """                      .htmx-indicator{opacity:0}                      .htmx-request .htmx-indicator{opacity:1; transition: opacity 200ms ease-in;}                      .htmx-request.htmx-indicator{opacity:1; transition: opacity 200ms ease-in;}                    """
sha256_hash = hashlib.sha256(content.encode()).digest()
print(base64.b64encode(sha256_hash).decode())
```

Append "sha256-" before this string, and here you are!
For your information, if you are using HTMX 2.0.3, the hash changed (because the CSS changed) and is now `sha256-bsV5JivYxvGywDAZ22EZJKBFip65Ng9xoJVLbBg7bdo=`

**Comment by GoodiesHQ** [comment]
Perfect! I whipped up a tiny application to do exactly this for me by hashing the files I put into it. My issue is just rendering it 

https://github.com/goodieshq/csphash

Step 1: Copy the CSS (including whitespace) from devtools. Just double click and copy.
![image](https://github.com/user-attachments/assets/533d54aa-6721-41bd-bcc7-9c76af4fee70)

Step 2: Put it into a text file, save it with no modifications.
![image](https://github.com/user-attachments/assets/6e62956a-b22e-4d85-be01-c8f98aa31678)

Step 3: run the csphash utility against it:
![image](https://github.com/user-attachments/assets/b1d99e4d-ca44-4ce1-b79d-b64ecadc119c)

Your way is faster, but I originally made the utility for hashing files. Might change it to read from stdin if no filename is provided.

Thank you!
